import os
import pandas as pd
import numpy as np
from numpy.linalg import norm
from dotenv import load_dotenv
from openai import OpenAI
import ast
import streamlit as st

# Load environment variables
load_dotenv()

# Initialize OpenAI client with API key
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Load the CSV with embeddings
df = pd.read_csv('embeddings.csv')

# Convert string back to numpy arrays in the 'embedding' column
df['embedding'] = df['embedding'].apply(ast.literal_eval).apply(np.array)

# Define a threshold for minimum similarity
SIMILARITY_THRESHOLD = 0.3  # Adjust this value based on experimentation

def get_embedding(text, model="text-embedding-3-small"):
    if not isinstance(text, str) or not text.strip():
        st.warning("Invalid or empty text input detected.")
        return np.zeros(1536)  # Return a zero vector for invalid input
    text = text.replace("\n", " ")  # Normalize newlines
    try:
        response = client.embeddings.create(input=text, model=model)
        response_dict = response.to_dict()  # Convert the response object to a dictionary
        embedding_vector = response_dict['data'][0]['embedding']
        return embedding_vector
    except Exception as e:
        st.error(f"An error occurred: {e}")
        return np.zeros(1536)  # Return a zero vector if there's an error

def safe_divide(a, b):
    return a / b if b != 0 else 0

def get_response(user_query):
    user_embedding = get_embedding(user_query, model='text-embedding-3-small')
    user_embedding_np = np.array(user_embedding)

    # Compute cosine similarity between user query and all document embeddings
    similarities = df['embedding'].apply(
        lambda x: np.dot(x, user_embedding_np) / safe_divide(norm(x) * norm(user_embedding_np), 1)
    )

    # Find the indices of the top 3 most similar documents
    top_indices = similarities.nlargest(3).index

    # Check if the top similarity score meets the threshold
    if similarities.iloc[top_indices[0]] < SIMILARITY_THRESHOLD:
        return "--", None  # None indicates no references

    context = ""
    references = []
    for index in top_indices:
        row = df.iloc[index]
        content = row['content']
        section_title = row['callout_title'] if pd.notna(row['callout_title']) and row['callout_title'].strip() else row['section_title']
        weblink = row.get("weblink", "")
        similarity = similarities.iloc[index]

        context += content + "\n\n"
        references.append({
            "filename": row['filename'],
            "title": section_title,
            "weblink": weblink,
            "similarity": similarity
        })

    if context.strip():
        try:
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": 
                    "Du bist ein hilfreicher und professioneller KI-Assistent. Du beantwortest ausschliesslich Fragen zum Lehrbuch \"Wissenschaftliches Arbeiten und Kommunizieren\". Deine Antworten sollen klar, korrekt, präzise und fachlich fundiert sein. Falls die gestellte Frage nicht auf Basis des Kontexts beantwortet werden kann, sage: \"Ich bin mir nicht sicher. Kannst du deine Frage umformulieren?\" Erfinde keine Informationen und nutze ausschliesslich den bereitgestellten Kontext."
                    },
                    {"role": "user", "content": f"Kontext: {context}\n\nFrage: {user_query}\nAntwort:"}
                ],
                temperature=0,
                max_tokens=800
            )

            if response.choices:
                message_text = response.choices[0].message.content.strip()
                return message_text, references
            else:
                return "No response generated by the model.", references
        except Exception as e:
            st.error(f"An error occurred during response generation: {e}")
            return "An error occurred while generating the response.", references
    else:
        return "Not enough content to generate a response.", references
