import os
import ast
import pandas as pd
import numpy as np
from numpy.linalg import norm
from dotenv import load_dotenv
from openai import OpenAI
import streamlit as st
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity as cosine_sim_sklearn

# Definitions
EMBEDDING_MODEL = "text-embedding-3-small"  # Default embedding model
CHAT_MODEL = "gpt-3.5-turbo"  # Default chat model
EMBEDDING_DIMENSION = 1536  # text-embedding-3-small dimension (has to be adjusted if using a different model)
SIMILARITY_THRESHOLD = 0.3 # Define a threshold for minimum similarity
MAX_TOKENS = 800
TEMPERATURE = 0
TOP_K = 5
ALPHA = 0.9  # Weight for semantic vs lexical similarity in hybrid retrieval (higher value = more semantic, lower value = more lexical)

# Load environment variables
load_dotenv()

# Initialize OpenAI client with API key
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Load the CSV with embeddings
df = pd.read_csv('embeddings.csv')

# Convert string back to numpy arrays in the 'embedding' column
df['embedding'] = df['embedding'].apply(ast.literal_eval).apply(np.array)

# Fit TF-IDF vectorizer on your document corpus
df["content"] = df["content"].astype(str).str.strip()
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df["content"])

# Embedding function
def get_embedding(text, model=EMBEDDING_MODEL):
    if not isinstance(text, str) or not text.strip():
        print("Invalid or empty text input detected, returning zero vector.")
        return np.zeros(EMBEDDING_DIMENSION)  # Return zero vector for invalid input
    text = text.replace("\n", " ")  # Normalize newlines
    try:
        response = client.embeddings.create(input=[text], model=model)
        response_dict = response.to_dict()
        return response_dict['data'][0]['embedding']
    except Exception as e:
        print(f"An error occurred during embedding: {e}")
        return np.zeros(EMBEDDING_DIMENSION)

# Cosine similarity function
def cosine_similarity_dense(a, b):
    """Calculate cosine similarity between two vectors."""
    norm_a = norm(a)
    norm_b = norm(b)
    if norm_a == 0 or norm_b == 0:
        return 0
    return np.dot(a, b) / (norm_a * norm_b)

# Hybrid Retrieval function
def retrieve_top_k(user_embedding, user_query, alpha=ALPHA):
    user_embedding_np = np.array(user_embedding)

    # Semantic similarity (existing cosine sim)
    semantic_similarities = df['embedding'].apply(lambda x: cosine_similarity_dense(x, user_embedding_np)).values

    # Lexical similarity (TF-IDF)
    user_tfidf = tfidf_vectorizer.transform([user_query])
    lexical_similarities = cosine_sim_sklearn(user_tfidf, tfidf_matrix).flatten()

    # Combine scores
    final_scores = alpha * semantic_similarities + (1 - alpha) * lexical_similarities

    # Top-K indices by hybrid score
    top_indices = np.argsort(final_scores)[-TOP_K:][::-1]

    context = ""
    references = []
    for index in top_indices:
        row = df.iloc[index]
        content = row['content']
        section_title = row['callout_title'] if pd.notna(row['callout_title']) and row['callout_title'].strip() else row['section_title']
        weblink = row.get("weblink", "")
        similarity = final_scores[index]

        context += content + "\n\n"
        references.append({
            "filename": row['filename'],
            "title": section_title,
            "weblink": weblink,
            "similarity": similarity
        })

    return context, references

# Answer generation function
def generate_answer(context, user_query):
    if not context.strip():
        return "Not enough content to generate a response."

    try:
        response = client.chat.completions.create(
            model=CHAT_MODEL,
            messages=[
                {"role": "system", "content": 
                 "Du bist ein hilfreicher und professioneller KI-Assistent. Du beantwortest ausschliesslich Fragen zum Lehrbuch \"Wissenschaftliches Arbeiten und Kommunizieren\". Deine Antworten sollen klar, korrekt, präzise und fachlich fundiert sein. Falls die gestellte Frage nicht auf Basis des Kontexts beantwortet werden kann, sage: \"Ich bin mir nicht sicher. Kannst du deine Frage umformulieren?\" Erfinde keine Informationen und nutze ausschliesslich den bereitgestellten Kontext."
                 },
                {"role": "user", "content": f"Kontext: {context}\n\nFrage: {user_query}\nAntwort:"}
            ],
            temperature=TEMPERATURE,
            max_tokens=MAX_TOKENS
        )

        if response.choices:
            return response.choices[0].message.content.strip()
        else:
            return "No response generated by the model."
    except Exception as e:
        return f"An error occurred while generating the response: {e}"

# Combined for app usage
def get_response(user_query, alpha=ALPHA):
    user_embedding = get_embedding(user_query)
    context, references = retrieve_top_k(user_embedding, user_query, alpha)

    # Check if top match is above threshold
    if not references or references[0]['similarity'] < SIMILARITY_THRESHOLD:
        return "--", None

    answer = generate_answer(context, user_query)
    return answer, references